# Generated by Django 3.2.25 on 2024-12-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_adi', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('resim', models.CharField(max_length=100)),
                ('anasayfa', models.BooleanField(default=False)),
                ('yeni_alan', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
