# Generated by Django 3.2.25 on 2024-12-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='yeni_alan',
        ),
    ]
