# Generated by Django 3.2.25 on 2024-12-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeler', '0002_remove_project_yeni_alan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projeler.category'),
            preserve_default=False,
        ),
    ]
